name: lyforum
description: Lyforum
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod: 0.14.0+4
  intl: ^0.17.0
dev_dependencies:
  build_runner:
  hive_generator:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

# flutter packages pub run build_runner build
